apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-app-ingress
  namespace: vote
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vote.polling.com
    - result.polling.com
    secretName: polling-tls
  rules:
  - host: vote.polling.com
    http:
      paths:
      - backend:
          service:
            name: vote-clusterip
            port:
              number: 5003
        path: /
        pathType: Prefix      
  - host: result.polling.com
    http:
      paths:
      - backend:
          service:
            name: result-clusterip
            port:
              number: 5004
        path: /
        pathType: Prefix


